apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: twitter-parser
description: My simplstic dev -> QA -> PROD pipeline
serialPipeline:
 stages:
 - targetId: ricc-development
   profiles: []
 - targetId: ricc-staging
   profiles: []
 - targetId: ricc-production
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: ricc-development
description: Riccardo development cluster
gke:
 cluster: projects/ric-cccwiki/locations/us-central1/clusters/quickstart-cluster-ricc-dev
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: ricc-staging
description: Riccardo near-production cluster
gke:
 cluster: projects/ric-cccwiki/locations/us-central1/clusters/quickstart-cluster-ricc-staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: ricc-production
description: Riccardo production cluster
gke:
 cluster: projects/ric-cccwiki/locations/us-central1/clusters/quickstart-cluster-ricc-production